version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: quotes
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env          # injects these as env vars in the container
    # you can still override specific ones here:
    environment:
      FX_PAIRS: USD/EUR,EUR/USD,EUR/MXN,USD/MXN

    ports: ["8080:8080"]

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /spec/openapi.yaml
    volumes:
      - ./openapi.yaml:/spec/openapi.yaml:ro
    ports: ["8081:8080"]